import type { Metadata } from "next";
import "./styles/global.scss";
import ClientProviders from "./context/react-query/ClientProviders";
import "bootstrap-icons/font/bootstrap-icons.css";


export const metadata: Metadata = {
  title: "Guilty Gear -Strive-",
  description: "Generated by create next app",
  icons: {
    icon:  { url: "/favicon.png", sizes: "32x32", type: "image/png" }
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClientProviders>
          {children}
        </ClientProviders>
      </body>
    </html>
  );
}
